name: Elixir CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs: 
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Elixir
              uses: actions/setup-elixir@v1
              with: 
                elixir-version: '1.14.2'
                otp-version: '26.2.1'
            - name: Install dependencies
              run: mix deps.get
            - name: Run tests
              run: mix test
            - name: format
              run: mix format